### ISSUE TITLE
Update nodejs version used in GitHub action

### ISSUE THREAD

**Issue by philipreimer** [eclipse-opensmartclide/smartclide-external-project-importer#4]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

See https://github.com/eclipse-opensmartclide/smartclide-external-project-importer/actions/runs/3315054381

**Comment by deanone** [comment]
@philipreimer is this something that can be resolved by changing any configuration of this repo, that requires admin rights?

**Comment by schlotze** [comment]
> However, enabling dependabot will require admin rights.

We could add the `dependabot.yml` file to the `.github` folder manually, wouldn't this work as well?=

**Comment by deanone** [comment]
> 

Yeap, that's what I was thinking too. This is another thing for which I will communicate with the Eclipse team.
